### ISSUE TITLE
Submit button is not showing under main menu when editing a request. 

### ISSUE THREAD

**Issue by CIManager** [WorkMAE/CEM-Integration#50] opened 2018-06-13 17:13 UTC
Submit button is not showing under the main menu when editing an existing request.

**Comment by FourUnbelievableCoolKids** [comment] 2018-07-11 16:09
It DOES appear, but only after the user changes tabs.

**Comment by WorkMAE** [comment] 2018-08-01 20:28
Fixed and duplicate of issue already listed

**Closed as completed by WorkMAE** 2018-08-01 20:28 UTC
Labels: duplicate, Pending Fix---Please Verify and Close!
